apiVersion: v1 
kind: Pod 
metadata: 
  name: pod-config 
spec: 
  containers: 
  - name: alpine 
    image: alpine 
    command: ["/bin/sh", "-c", "echo $MENSAJE && sleep 3600"] 
    env: 
    - name: MENSAJE 
      valueFrom: 
        configMapKeyRef: 
          name: mi-config 
          key: MENSAJE 